# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{qusion}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan DeLeo"]
  s.date = %q{2010-01-17}
  s.description = %q{Rails wrapper around the AMQP gem}
  s.email = %q{dan@kallistec.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/qusion.rb",
     "lib/qusion/amqp.rb",
     "lib/qusion/amqp_config.rb",
     "lib/qusion/channel_pool.rb",
     "lib/qusion/em.rb",
     "lib/qusion/server_spy.rb",
     "spec/fixtures/framework-amqp.yml",
     "spec/fixtures/hardcoded-amqp.yml",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/amqp_config_spec.rb",
     "spec/unit/amqp_spec.rb",
     "spec/unit/channel_pool_spec.rb",
     "spec/unit/em_spec.rb",
     "spec/unit/qusion_spec.rb",
     "spec/unit/server_spy_spec.rb"
  ]
  s.homepage = %q{http://github.com/danielsdeleo/qusion}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Using AMQP as a Queuing Backend for Web Apps Should Be Easy}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/unit/amqp_config_spec.rb",
     "spec/unit/amqp_spec.rb",
     "spec/unit/channel_pool_spec.rb",
     "spec/unit/em_spec.rb",
     "spec/unit/qusion_spec.rb",
     "spec/unit/server_spy_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 2.3.0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 2.3.0"])
  end
end

